/**
 * Paylink — Anchor Program Utilities
 *
 * Provides the Anchor program instance and PDA derivation helpers.
 */
import { PublicKey } from '@solana/web3.js';
import { Program, AnchorProvider } from '@coral-xyz/anchor';
import { PROGRAM_ID } from './constants';

// Minimal IDL — matches the hardened lib.rs
// In production, this is generated by `anchor build`
export const IDL = {
  version: '0.1.0',
  name: 'paylink',
  instructions: [
    {
      name: 'createLink',
      accounts: [
        { name: 'sender', isMut: true, isSigner: true },
        { name: 'escrowAccount', isMut: true, isSigner: false },
        { name: 'escrowTokenAccount', isMut: true, isSigner: false },
        { name: 'senderTokenAccount', isMut: true, isSigner: false },
        { name: 'tokenMint', isMut: false, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'amount', type: 'u64' },
        { name: 'claimSeed', type: { array: ['u8', 32] } },
        { name: 'expiryTs', type: 'i64' },
      ],
    },
    {
      name: 'claim',
      accounts: [
        { name: 'recipient', isMut: false, isSigner: true },
        { name: 'sender', isMut: true, isSigner: false },
        { name: 'escrowAccount', isMut: true, isSigner: false },
        { name: 'escrowTokenAccount', isMut: true, isSigner: false },
        { name: 'recipientTokenAccount', isMut: true, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'claimSeed', type: { array: ['u8', 32] } },
      ],
    },
    {
      name: 'reclaim',
      accounts: [
        { name: 'sender', isMut: true, isSigner: true },
        { name: 'escrowAccount', isMut: true, isSigner: false },
        { name: 'escrowTokenAccount', isMut: true, isSigner: false },
        { name: 'senderTokenAccount', isMut: true, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'claimSeed', type: { array: ['u8', 32] } },
      ],
    },
  ],
  accounts: [
    {
      name: 'EscrowAccount',
      type: {
        kind: 'struct',
        fields: [
          { name: 'sender', type: 'publicKey' },
          { name: 'mint', type: 'publicKey' },
          { name: 'amount', type: 'u64' },
          { name: 'claimSeed', type: { array: ['u8', 32] } },
          { name: 'expiryTs', type: 'i64' },
          { name: 'claimed', type: 'bool' },
          { name: 'bump', type: 'u8' },
        ],
      },
    },
  ],
  errors: [
    { code: 6000, name: 'AlreadyClaimed', msg: 'This link has already been claimed.' },
    { code: 6001, name: 'LinkExpired', msg: 'This link has expired.' },
    { code: 6002, name: 'NotYetExpired', msg: 'Link has not yet expired.' },
    { code: 6003, name: 'Unauthorized', msg: 'Only the original sender can reclaim.' },
    { code: 6004, name: 'ZeroAmount', msg: 'Amount must be greater than zero.' },
    { code: 6005, name: 'ExpiryInPast', msg: 'Expiry timestamp must be in the future.' },
    { code: 6006, name: 'InvalidTokenAccountOwner', msg: 'Token account owner does not match expected wallet.' },
    { code: 6007, name: 'MintMismatch', msg: 'Token mint does not match the escrow mint.' },
  ],
};

const programId = new PublicKey(PROGRAM_ID);

/**
 * Get the Anchor program instance from a wallet + connection.
 */
export function getProgram(connection, wallet) {
  const provider = new AnchorProvider(connection, wallet, {
    commitment: 'confirmed',
  });
  return new Program(IDL, programId, provider);
}

/**
 * Derive the escrow account PDA.
 */
export function getEscrowPDA(claimSeed) {
  return PublicKey.findProgramAddressSync(
    [Buffer.from('escrow'), Buffer.from(claimSeed)],
    programId
  );
}

/**
 * Derive the escrow token account PDA.
 */
export function getEscrowTokenPDA(claimSeed) {
  return PublicKey.findProgramAddressSync(
    [Buffer.from('escrow-token'), Buffer.from(claimSeed)],
    programId
  );
}

/**
 * Map Anchor error codes to user-friendly messages.
 */
export function getErrorMessage(error) {
  if (!error) return 'An unknown error occurred.';

  const errorStr = error.toString();

  // Check for Anchor program errors
  const anchorError = IDL.errors.find(e =>
    errorStr.includes(e.code.toString()) || errorStr.includes(e.name)
  );
  if (anchorError) return anchorError.msg;

  // Common Solana errors
  if (errorStr.includes('Insufficient funds')) return 'Insufficient token balance.';
  if (errorStr.includes('User rejected')) return 'Transaction was rejected.';
  if (errorStr.includes('Blockhash not found')) return 'Network congestion. Please try again.';

  if (error instanceof Error) {
    return `Debug Error: ${error.message}`;
  }

  return `Raw Error: ${errorStr}`;
}
